version: '3.8'

networks:
  webnet_secret-santa:
    driver: bridge

services:

  secret-santa-ui:
    image: "secret-santa-ui"
    depends_on:
      - secret-santa-backend
    ports:
      - "3000:80"
    networks:
      - webnet_secret-santa
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  secret-santa-backend:
    image: "secret-santa-backend"
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    networks:
      - webnet_secret-santa